### ISSUE TITLE
Deploying to Domain Subdirectory Error

### ISSUE THREAD

**Issue by RyanSCodes** [pinterest/querybook#1249]
Hi Querybook people,

I'm trying to host the Querybook app on our AWS EKS cluster using the Helm chart in the repo. Our network domain name is 'mydomain.co.uk', and I would like to host this app at 'mydomain.co.uk/querybook/'. 

In helm/values.yaml I set the ingress as:
```
ingress:
  enabled: true
  ingressClassName: ~
  annotations: {}
  path: /querybook/
  pathType: Prefix
  hosts: 
    - mydomain.co.uk
  tls: []
```
and the PUBLIC_URL environmental variable as:
```
extraEnv:
  PUBLIC_URL: https://mydomain.co.uk/querybook
```

But when I deploy the app, the webpage is sending requests like 'mydomain.co.uk/build/...', 'mydomain.co.uk/ds/...', and does not seem to be deployed to the domain subdirectory.
